# Generated by Django 3.0.3 on 2020-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
