# Generated by Django 3.0.2 on 2020-03-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignmentupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
