# Generated by Django 3.0.3 on 2020-03-05 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0002_assignmentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='submitted_by',
            field=models.ForeignKey(default='no owner', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
