# Generated by Django 3.0.3 on 2020-03-05 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.AlterField(
            model_name='module',
            name='module_Id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='module',
            name='students',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(through='accounts.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
