# Generated by Django 3.0.3 on 2020-03-06 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_uploadfile_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=15)),
                ('submission_id', models.CharField(max_length=15)),
                ('assignment_id', models.CharField(max_length=15)),
                ('result', models.CharField(max_length=15)),
                ('feedback', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='id',
        ),
        migrations.AddField(
            model_name='assignmentupload',
            name='assignment_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='assignment_id',
            field=models.CharField(default=datetime.datetime(2020, 3, 6, 2, 20, 23, 672653, tzinfo=utc), max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='module_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='submission_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
